#!/bin/bash
echo "Generating blog posts..."
echo "Make sure your dev server is running: npm run dev"
echo ""
echo "Then run this in another terminal:"
echo ""
echo "curl -X POST http://localhost:3000/api/generate/blog \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"type\": \"bulk\", \"saveToFile\": true}'"
echo ""
echo "After generation completes, commit the file:"
echo "git add data/generated-blog-posts.json"
echo "git commit -m 'Add generated blog posts'"
echo "git push"
